function(modify_target_for_playdate TARGET)
    if (TOOLCHAIN STREQUAL "armgcc")
        target_compile_options(${TARGET} PUBLIC $<$<CONFIG:DEBUG>:-O0>)
        target_compile_options(${TARGET} PUBLIC $<$<CONFIG:RELEASE>:-O3>)
        target_compile_options(${TARGET} PUBLIC ${MCFLAGS})
        target_compile_options(${TARGET} PUBLIC -falign-functions=16 -fomit-frame-pointer)
        target_compile_options(${TARGET} PUBLIC -gdwarf-2)
        target_compile_options(${TARGET} PUBLIC -fverbose-asm)
        target_compile_options(${TARGET} PUBLIC -ffunction-sections -fdata-sections)
        target_compile_options(${TARGET} PUBLIC -mword-relocations -fno-common)
    endif()
endfunction()